# Generated by Django 3.0.8 on 2020-07-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='discount',
            field=models.IntegerField(verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
