# Generated by Django 3.0.8 on 2020-07-08 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_auto_20200706_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='discount',
        ),
    ]
